### ISSUE TITLE
Update README badges as part of automated release

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask-docker#183]
Our `README` has several badges for the most recent release (e.g. ![](https://img.shields.io/badge/daskdev%2Fdask-2021.8.1-blue)). It would be great if these badges were updated as part of our automated release procedure (xref https://github.com/dask/dask-docker/pull/182)

**Comment by jacobtomlinson** [comment]
Hrm I had hoped this would happen, but I guess not. Ill look into it.

**Comment by jakirkham** [comment]
Had tried to do this with PR ( https://github.com/dask/dask-docker/pull/192 ) and then PR ( https://github.com/dask/dask-docker/pull/195 ), but it appears it is still not updating them ( https://github.com/dask/dask-docker/pull/196 ).

Am guessing we want this regex ( https://github.com/dask/dask-docker/pull/192/files#r735042744 ) added [to the find string]( https://github.com/dask/dask-docker/blob/5bd1d001f7c6c2e4bbff4133308766c711222d9e/.github/workflows/watch-conda-forge.yml#L26 ) and some changes [to the replacement string]( https://github.com/dask/dask-docker/blob/5bd1d001f7c6c2e4bbff4133308766c711222d9e/.github/workflows/watch-conda-forge.yml#L27 ).

**Comment by jrbourbeau** [comment]
Looks like this was addressed by https://github.com/dask/dask-docker/pull/195. I'll close this issue for now and we can re-open as needed

**Comment by jakirkham** [comment]
Unfortunately it is still not working 😞

Think the regex needs some work still as noted above

**Comment by jakirkham** [comment]
Maybe this will be useful for debugging GH Actions locally

https://github.com/nektos/act

**Comment by jakirkham** [comment]
Is there some way we need to structure the files included?

https://github.com/dask/dask-docker/blob/d36602cd96fd8e2433597f1003ee14be4f88a33f/.github/workflows/watch-conda-forge.yml#L25
